name: "Bug Report"
description: Report an issue or unexpected behavior in CPP-CLOC
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in **CPP-CLOC**!  
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: title
    attributes:
      label: Short Summary
      placeholder: "Analyzer miscounts code lines with multiline comments"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: |
        Describe what you did, what happened, and what you expected.
        Include error messages, if any.
      description: |
        Logs, code snippets, and screenshots help a lot.

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run CPP-CLOC on the file `example.ts`
        2. Observe miscounted lines of code and comments
        3. Expected counts should match cloc output

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      placeholder: |
        Paste the shortest code snippet that triggers the bug.
        Example:
        console.log();
        /* multiline comment */
        let a: number = 5;

  - type: input
    id: cpp-version
    attributes:
      label: C++ Version / Compiler
      placeholder: "g++ 12 / MSVC 19 / clang 16"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 11 / macOS Ventura / Ubuntu 22.04"

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I'm using the latest version of CPP-CLOC
        - label: I checked the README and Known Limitations
        - label: I included error logs or screenshots if available
