name: "Code Enhancement / Refactor"
description: Suggest improvements or refactoring for CPP-CLOC codebase
labels: [enhancement, refactor]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the **CPP-CLOC** codebase?  
        This could include refactoring functions, improving readability, or optimizing performance.  
        Please provide details below.

  - type: textarea
    id: enhancement-summary
    attributes:
      label: Enhancement Summary
      placeholder: "Refactor the analyzer to handle multiline comments more efficiently"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Why and How?
      placeholder: |
        Why is this enhancement needed?  
        What changes do you suggest, and how should they improve CPP-CLOC?
    validations:
      required: true
